apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: insurance-regression-ml-api
  name: insurance-regression-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-regression
  template:
    metadata:
      labels:
        app: insurance-regression
    spec:
      containers:
      - image: aguennoune/fastapi-insurance-regression:1.0.5
        imagePullPolicy: IfNotPresent
        name: insurance-regression-container
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-credentials
