apiVersion: v1
kind: Service
metadata:
  labels:
    app: insurance-regression-svc
  name: insurance-regression-svc
spec:
  ports:
  - name: predict
    nodePort: 30000
    port: 80
    targetPort: http
  selector:
    app: insurance-regression
  type: NodePort
