apiVersion: v1
kind: ConfigMap
metadata:
  name: streamlit-configmap
  namespace: ns-streamlit
data:
  conf.json: |
    {
      "age": 32,
      "sex": "male",
      "bmi": 28.880,
      "children": 0,
      "smoker": yes,
      "region": "northwest"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  namespace: ns-streamlit
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git:2.40.1
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache git && \
          git clone --single-branch --depth 1 https://github.com/aguennoune/pycaret-frontend-k8s-streamlit.git /app && \
          cd /app && \
          pip install -r src/frontend/k8s_streamlit/requirements.txt && \
          chmod 644 src/frontend/k8s_streamlit/insurance_gbr_model_23122020.pkl
        volumeMounts:
        - mountPath: /app
          name: streamlit-volume
        - mountPath: /app
          name: app-volume
      containers:
      - image: aguennoune/pycaret-k8s-streamlit:1.10.0
        imagePullPolicy: Always
        name: streamlit
        ports:
        - containerPort: 8501
          protocol: TCP
          name: http
        command: ["streamlit", "run", "/tmp/app/src/frontend/k8s_streamlit/app.py", "--server.port=8501", "--server.address=127.0.0.1"]
        volumeMounts:
        - mountPath: /app
          name: streamlit-volume
        - mountPath: /app/src/frontend/k8s_streamlit/insurance_gbr_model_23122020.pkl
          name: streamlit-volume
          subPath: insurance_gbr_model_23122020.pkl
      imagePullSecrets:
      - name: registry-credentials
      volumes:
      - name: streamlit-volume
        configMap:
          name: streamlit-configmap
      - name: app-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-svc
  labels:
    app: streamlit
  namespace: ns-streamlit
spec:
  type: ClusterIP
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8501
