apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    app: jupyter
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  initContainers:
  - name: git-clone
    image: alpine/git
    args:
    - clone
    - --single-branch
    - --
    - https://github.com/pycaret/examples.git
    - /data
    volumeMounts:
    - mountPath: /data
      name: notebook-volume
  containers:
  - name: jupyter
    image: jupyter/base-notebook:latest
    ports:
    - containerPort: 8888
      protocol: TCP
      name: http
    volumeMounts:
    - mountPath: /root
      name: notebook-volume
  volumes:
  - name: notebook-volume
    emptyDir: {}
